### ISSUE TITLE
404 Client Error: Not Found for url: http://localhost:8080/api/config/devices/_operations/sync-from

### ISSUE THREAD

**Issue by abhishekm8669** [NSO-developer/netdevops-demo#1]
Hello,

I am trying to built this netdevops demo on my local machine everything is going good but at the time of ansible generation it is providing the exception and the make demo command is failing. My console output is as follows:

:~/netdevops-demo$ make demo
pip install -r requirements.txt
Collecting ansible==2.5.0 (from -r requirements.txt (line 1))
Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting bcrypt==3.1.4 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/2e/5a/2abeae20ce294fe6bf63da0e0b5a885c788e1360bbd124edcc0429678a59/bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cffi==1.11.5 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cryptography==2.2.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/dd/c2/3a5bfefb25690725824ade71e6b65449f0a9f4b29702cce10560f786ebf6/cryptography-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting idna==2.6 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting ipaddress==1.0.22 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting Jinja2==2.10 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 10))
Collecting paramiko==2.4.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl
Collecting pyasn1==0.4.2 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pycparser==2.18 (from -r requirements.txt (line 13))
Collecting PyNaCl==1.2.1 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/80/3d/d709b9fbd69e21dd3a4d34eb690c5484094699e03b7447bc7eb173cfd7b6/PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting PyYAML==3.12 (from -r requirements.txt (line 15))
Collecting requests==2.18.4 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting six==1.11.0 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting setuptools (from ansible==2.5.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: pycparser, cffi, enum34, idna, asn1crypto, six, ipaddress, cryptography, PyNaCl, pyasn1, bcrypt, paramiko, MarkupSafe, Jinja2, setuptools, PyYAML, ansible, urllib3, certifi, chardet, requests
Successfully installed Jinja2-2.10 MarkupSafe-1.0 PyNaCl-1.2.1 PyYAML-3.12 ansible-2.5.0 asn1crypto-0.24.0 bcrypt-3.1.4 certifi-2020.6.20 cffi-1.11.5 chardet-3.0.4 cryptography-2.2.2 enum34-1.1.6 idna-2.6 ipaddress-1.0.22 paramiko-2.4.1 pyasn1-0.4.2 pycparser-2.18 requests-2.18.4 setuptools-44.1.1 six-1.11.0 urllib3-1.22
ncs-netsim create-network /home/ubuntu/ncs-run/packages/cisco-iosxr-cli-3.5 3 router
DEVICE router0 CREATED
DEVICE router1 CREATED
DEVICE router2 CREATED
ncs-netsim start
DEVICE router0 OK STARTED
DEVICE router1 OK STARTED
DEVICE router2 OK STARTED
ncs-setup --dest .
Using netsim dir /home/ubuntu/netdevops-demo/netsim
ncs
python generate_ansible.py
Syncing Configuration from Devices
Traceback (most recent call last):
  File "generate_ansible.py", line 57, in <module>
    main()
  File "generate_ansible.py", line 27, in main
    nso.sync_from()
  File "/home/ubuntu/netdevops-demo/helpers/nso.py", line 69, in sync_from
    resp = self.post(url)
  File "/home/ubuntu/netdevops-demo/helpers/nso.py", line 62, in post
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/api/config/devices/_operations/sync-from
Makefile:17: recipe for target 'ansible' failed
make: *** [ansible] Error 1

**Comment by jabelk** [comment]
this should be fixed by the latest PR moving from REST -> RESTCONF API
